Repository amosproj/amos2022ws04-specitem-database, pull requests merged in 2023-02, with the labels that each got.

#168 Dev
  code/pom.xml
  code/src/main/java/amos/specitemdatabase/controller/Controller.java
  code/src/main/java/amos/specitemdatabase/model/SpecItem.java
  code/src/main/java/amos/specitemdatabase/model/SpecItemBuilder.java
  code/src/main/java/amos/specitemdatabase/repo/SpecItemRepo.java
  code/src/main/java/amos/specitemdatabase/service/SpecItemService.java
  code/src/test/java/amos/specitemdatabase/controller/ControllerRaceConditionTest.java
Labels: bug, documentation, frontend, backend

#169 Twittig fix frontend
  frontend/specitem/src/pages/specitem_history.js
  frontend/specitem/src/pages/specitem_page.js
  frontend/specitem/src/pages/specitems_page.js
Labels: frontend

#176 Kevin issue171
  code/src/main/java/amos/specitemdatabase/model/Category.java
  code/src/main/java/amos/specitemdatabase/repo/DocumentRepo.java
  code/src/main/java/amos/specitemdatabase/repo/SpecItemRepo.java
  code/src/main/java/amos/specitemdatabase/service/SpecItemService.java
Labels: backend, refactoring
