Repository amosproj/amos2022ws04-specitem-database, pull requests merged in 2023-01, with the labels that each got.

#137 Georgi issue132
  code/src/main/java/amos/specitemdatabase/controller/Controller.java
  code/src/main/java/amos/specitemdatabase/importer/SpecItemParser.java
  code/src/main/java/amos/specitemdatabase/model/SpecItemBuilder.java
  code/src/main/java/amos/specitemdatabase/service/SpecItemService.java
  frontend/specitem/src/components/tagsinput.js
  frontend/specitem/src/pages/main_page.js
  frontend/specitem/src/pages/specitem_history.js
  frontend/specitem/src/pages/specitem_page.js
  frontend/specitem/src/pages/specitems_page.js
Labels: frontend

#139 Twittig issue130
  code/src/main/java/amos/specitemdatabase/service/SpecItemService.java
Labels: backend

#138 Kevin issue114
  code/src/main/java/amos/specitemdatabase/controller/Controller.java
  code/src/main/java/amos/specitemdatabase/service/SpecItemService.java
  frontend/specitem/src/pages/specitems_page.js
Labels: frontend, backend

#151 Kevin issue146
  Deliverables/sprint-11/feature-board.png
  Deliverables/sprint-11/planning-document.pdf
  code/src/main/java/amos/specitemdatabase/controller/Controller.java
  code/src/main/java/amos/specitemdatabase/repo/SpecItemRepo.java
  code/src/main/java/amos/specitemdatabase/service/SpecItemService.java
Labels: backend

#152 Bug fix
  code/src/main/java/amos/specitemdatabase/controller/Controller.java
  code/src/main/java/amos/specitemdatabase/repo/DocumentRepo.java
  code/src/main/java/amos/specitemdatabase/repo/SpecItemRepo.java
  code/src/main/java/amos/specitemdatabase/service/SpecItemService.java
Labels: bug, backend

#153 Bug fix part 2
  code/src/main/java/amos/specitemdatabase/repo/DocumentRepo.java
  code/src/main/java/amos/specitemdatabase/service/SpecItemService.java
Labels: bug, backend

#154 Twittig issue116
  code/src/main/java/amos/specitemdatabase/controller/Controller.java
  frontend/specitem/src/components/collapseContent.js
  frontend/specitem/src/pages/specitem_history.js
  frontend/specitem/src/pages/specitem_page.js
  frontend/specitem/src/pages/specitems_page.js
Labels: frontend

#156 Twittig issue116
  frontend/specitem/src/components/collapseContent.js
  frontend/specitem/src/pages/specitem_history.js
  frontend/specitem/src/pages/specitem_page.js
  frontend/specitem/src/pages/specitems_page.js
Labels: frontend

#161 Handling race conditions in the tag addition function
  code/src/main/java/amos/specitemdatabase/controller/Controller.java
  code/src/main/java/amos/specitemdatabase/model/SpecItem.java
  code/src/main/java/amos/specitemdatabase/model/SpecItemId.java
  code/src/main/java/amos/specitemdatabase/model/TagInfo.java
  code/src/main/java/amos/specitemdatabase/repo/SpecItemRepo.java
  code/src/main/java/amos/specitemdatabase/repo/TagsRepo.java
  code/src/main/java/amos/specitemdatabase/service/SpecItemService.java
  code/src/main/java/amos/specitemdatabase/tagservice/TagService.java
  code/src/main/java/amos/specitemdatabase/tagservice/TagServiceImpl.java
  code/src/test/java/amos/specitemdatabase/service/SpecitemsComparatorTest.java
  code/src/test/java/amos/specitemdatabase/service/TaggingMechanismTest.java
  code/src/test/java/amos/specitemdatabase/service/TaggingRaceConditionsTest.java
Labels: backend

#166 Kevin issue159
  Deliverables/sprint-12/feature-board.png
  Deliverables/sprint-12/planning-document.pdf
  code/src/main/java/amos/specitemdatabase/controller/Controller.java
  code/src/main/java/amos/specitemdatabase/model/SpecItem.java
  code/src/main/java/amos/specitemdatabase/model/SpecItemBuilder.java
  code/src/main/java/amos/specitemdatabase/repo/SpecItemRepo.java
  code/src/main/java/amos/specitemdatabase/service/SpecItemService.java
Labels: backend
